Added few points, fixed typo
ZaidPathan/ThingsThatSlowDownTheProject pull request #1
Opened 2018-10-05 11:53 UTC by bhvk121

2018-10-05 13:28 UTC, ZaidSA requested changes
Thanks for contribution, please check comments.

2018-10-05 13:28 UTC, ZaidSA commented on README.md
> +# 8. Project complexity under-estimation
Thanks for contribution, can we make it more simpler please?

2018-10-05 13:28 UTC, ZaidSA commented on README.md
> +# 11. Improper resource utilization / improper tasks allocation
Should it be 2 different points?

2018-10-05 13:28 UTC, ZaidSA commented on README.md
> +# 12. unforeseen technical challenges
unforeseen should be Unforeseen

2018-10-06 13:48 UTC, bhvk121 commented
Addressed.

2018-10-08 06:47 UTC, ZaidSA approved these changes

2018-10-08 06:47 UTC, merged